- name: Show how to hide creds
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: true    # nothing shows up to standard out

  vars:
    # by default we will look for the environmental var MYPASSWORD
    mypassword: "{{ lookup('ansible.builtin.env', 'MYPASSWORD') }}"

  tasks:
    - name: display whatever is read in as MYPASSWORD
      debug:
        var: mypassword
